declare let player: YouTubePlayer;
declare let mytimer: number;
declare const $: (selector: string) => HTMLElement;
declare const btn_prev: HTMLButtonElement;
declare const btn_play: HTMLButtonElement;
declare const btn_pause: HTMLButtonElement;
declare const btn_next: HTMLButtonElement;
declare const btn_stop: HTMLButtonElement;
declare const playerWrapper: HTMLDivElement;
declare const thumbWrapper: HTMLDivElement;
declare const progressBarWrapper: HTMLDivElement;
declare const progressBar: HTMLDivElement;
declare const thumb: HTMLImageElement;
declare const playerControl: {
    autoPlay: boolean;
    video: boolean;
    playlist: string[];
    playlistIndex: number;
    state: number;
    nbSongs: () => number;
    getCurrentSong: () => string;
    play: () => void;
    pause: () => void;
    stop: () => void;
    showPlay: (showPlay: boolean) => void;
    prev: () => void;
    next: () => void;
    timer: (e: MouseEvent) => void;
    changeVideo: () => void;
    changeThumb: () => void;
    progress: (percent: number) => void;
    setDisplay: () => void;
};
declare function onYouTubeIframeAPIReady(): void;
declare function onPlayerReady(event: {
    target: YouTubePlayer;
}): void;
declare function onPlayerStateChange(event: {
    data: number;
}): void;
